-- Migration: Add tags column to urls table
-- Date: 2024-01-01
-- Feature: F-006 - Tag Auto-generation

-- Add tags column to urls table
ALTER TABLE urls
ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';

-- Create GIN index for efficient tag searching
CREATE INDEX IF NOT EXISTS idx_urls_tags ON urls USING GIN(tags);

-- Add comment for documentation
COMMENT ON COLUMN urls.tags IS 'Array of tags generated by LLM for article categorization';